apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: sink-snowflake
  labels:
    strimzi.io/cluster: kconnect
spec:
  autoRestart:
    enabled: true
  class: br.com.datastreambrasil.v3.SnowflakeSinkConnector
  tasksMax: 1
  config:
    topics: "cdc.test.dbo.events"
    url: "jdbc:snowflake://xxxxxx.snowflakecomputing.com?schema=LZ_IH&db=DATB200D&CLIENT_SESSION_KEEP_ALIVE=TRUE"
    user: "xxxxx"
    password: "xxxxx"
    stage: "events"
    table: "events"
    schema: "LZ_IH"
    key.converter: "io.confluent.connect.avro.AvroConverter"
    key.converter.schema.registry.url: "http://host.minikube.internal:8085"
    key.converter.schemas.enable: true
    value.converter: "io.confluent.connect.avro.AvroConverter"
    value.converter.schema.registry.url: "http://host.minikube.internal:8085"
    value.converter.schemas.enable: true